application: lazyhacking
version: 1
runtime: go
api_version: go1

inbound_services:
  - channel_presence

handlers:
- url: /favicon\.ico
  static_files: app/static/images/favicon.ico
  upload: app/static/images/favicon\.ico

- url: /bower_components
  static_dir: node_modules/
  
- url: /app\.apk
  static_files: static/apks/app.apk
  upload: static/apks/app\.apk

- url: /+
  static_dir: webApp/www/

- url: /.*
  script: _go_app

